# Generated by Django 3.0.9 on 2020-11-10 02:30

from django.db import migrations, models
import people.apps.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='ExperienceType',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de experiencia',
                'verbose_name_plural': 'Tipos de experiencias',
            },
        ),
        migrations.CreateModel(
            name='LaborRelationship',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Relacion laboral',
                'verbose_name_plural': 'Relaciones laborales',
            },
        ),
        migrations.CreateModel(
            name='ReasonSeparation',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Razon de separacion',
                'verbose_name_plural': 'Razones de separacion',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
            },
        ),
    ]
