# Generated by Django 3.0.9 on 2021-01-26 16:52

from django.db import migrations, models
import people.apps.functions


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
