# Generated by Django 3.0.9 on 2021-01-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_documenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
    ]
