# Generated by Django 3.0.9 on 2020-09-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='Llave secreta')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente id')),
                ('url_server', models.URLField(blank=True, null=True, verbose_name='URL del servicio')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
