# Generated by Django 3.0.11 on 2020-11-02 20:59

from django.db import migrations, models
import django.db.models.deletion
import people.apps.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=150, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(max_length=150, verbose_name='Apellido materno')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('imss', models.CharField(max_length=11, verbose_name='IMSS')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='GeneralPerson',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('place_birth', models.DateField(verbose_name='Lugar de nacimiento')),
                ('nationality', models.CharField(max_length=150, verbose_name='Nacionalidad')),
                ('other_nationality', models.CharField(max_length=150, verbose_name='Otra nacionaldiad')),
                ('availability_travel', models.BooleanField(default=False, verbose_name='Disponibilidad para viajar')),
                ('availability_change_residence', models.BooleanField(default=False, verbose_name='Disponibilidad para cambio de residencia')),
                ('allergies', models.CharField(max_length=500, verbose_name='Alergias')),
                ('blood_type', models.CharField(max_length=10, verbose_name='Tipo de sangre')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'General de persona',
                'verbose_name_plural': 'General de personas',
            },
        ),
    ]
