# Generated by Django 3.0.9 on 2020-11-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalperson',
            options={'verbose_name': 'General', 'verbose_name_plural': 'Generales'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='¿Eliminado?'),
        ),
    ]
