# Generated by Django 3.0.9 on 2020-11-03 19:02

from django.db import migrations, models
import django.db.models.deletion
import people.apps.functions


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20201103_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de puesto')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo de puesto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_assignable', models.BooleanField(default=True, verbose_name='¿Asignable a personas?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Tipo de persona',
                'verbose_name_plural': 'Tipos de personas',
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='paternal_surname',
            new_name='flast_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='maternal_surname',
            new_name='mlast_name',
        ),
        migrations.AddField(
            model_name='person',
            name='khonnect_id',
            field=models.CharField(default=1, help_text='Informacion que proviene del microservicio khonnect', max_length=40, verbose_name='Khonnect id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imss',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='IMSS'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Job', verbose_name='Puesto de trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.PersonType', verbose_name='Tipo de persona'),
            preserve_default=False,
        ),
    ]
