# Generated by Django 3.0.9 on 2020-11-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20201103_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalperson',
            name='allergies',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='availability_change_residence',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Disponibilidad para cambio de residencia'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='availability_travel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Disponibilidad para viajar'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Otra nacionaldiad'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='generalperson',
            name='place_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Lugar de nacimiento'),
        ),
    ]
