# Generated by Django 3.0.9 on 2020-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20201103_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalperson',
            name='place_birth',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar de nacimiento'),
        ),
    ]
