# Generated by Django 3.0.9 on 2020-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20201104_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='khonnect_id',
            field=models.CharField(blank=True, help_text='Informacion que proviene del microservicio khonnect', max_length=40, null=True, verbose_name='Khonnect id'),
        ),
    ]
