# Generated by Django 3.0.9 on 2020-11-10 02:30

from django.db import migrations, models
import django.db.models.deletion
import people.apps.functions


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('person', '0006_auto_20201105_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle')),
                ('numberOne', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero uno')),
                ('numberTwo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero dos')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edificio')),
                ('reference', models.IntegerField(blank=True, null=True, verbose_name='Referencia')),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo postal')),
                ('suburb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suburbio')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escuela')),
                ('since', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('until', models.DateTimeField(verbose_name='Fecha de termino')),
                ('accreditation_document', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documeto de acreditacion')),
                ('currently_studing', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estudia actualmente')),
                ('completed_period', models.IntegerField(blank=True, null=True, verbose_name='Periodo completado')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Formacion',
                'verbose_name_plural': 'Formaciones',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=40, verbose_name='Nombre completo')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Relationship', verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='ExperienceJob',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('since', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('until', models.DateTimeField(verbose_name='Fecha de termino')),
                ('turn', models.CharField(max_length=150, verbose_name='Giro empresarial')),
                ('function', models.CharField(max_length=350, verbose_name='Funciones')),
                ('startin_salary', models.CharField(max_length=150, verbose_name='Salario incial')),
                ('last_salary', models.CharField(max_length=150, verbose_name='Salario final')),
                ('immediate_boos', models.CharField(max_length=150, verbose_name='Jefe inmediato')),
                ('addres_company', models.CharField(max_length=300, verbose_name='Direccion de la empresa')),
                ('phone_company', models.CharField(max_length=40, verbose_name='Telefono de la empresa')),
                ('notes', models.CharField(max_length=300, verbose_name='Notas')),
                ('cv', models.CharField(max_length=300, verbose_name='Curriculum')),
                ('experience_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.ExperienceType', verbose_name='Tipo de experiencia')),
                ('labor_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.LaborRelationship', verbose_name='Relacion laboral')),
                ('reason_separation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.ReasonSeparation', verbose_name='Motivo de separacion')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
            },
        ),
        migrations.CreateModel(
            name='ContactEmergency',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone_one', models.CharField(max_length=150, verbose_name='Numero telefonico 1')),
                ('phone_two', models.CharField(max_length=150, verbose_name='Numero telefonico 2')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Address', verbose_name='Direccion')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Relationship', verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero de cuenta')),
                ('interbank_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clave interbancaria')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Bank', verbose_name='Banco')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Numero de cuenta',
                'verbose_name_plural': 'Numeros de cuentas',
            },
        ),
    ]
