# Generated by Django 3.0.9 on 2020-11-11 16:18

from django.db import migrations
import easy_thumbnails.fields
import people.apps.person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_address_bankaccount_contactemergency_experiencejob_family_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalperson',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=people.apps.person.models.GeneralPerson.upload_photo, verbose_name='Fotografia'),
        ),
    ]
