# Generated by Django 3.0.9 on 2020-11-11 16:43

from django.db import migrations
import easy_thumbnails.fields
import people.apps.person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_generalperson_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalperson',
            name='cv',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, null=True, upload_to=people.apps.person.models.GeneralPerson.upload_photo, verbose_name='Curriculum vitae'),
        ),
    ]
