# Generated by Django 3.0.9 on 2020-11-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_generalperson_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalperson',
            name='cv',
        ),
    ]
