# Generated by Django 3.0.9 on 2020-11-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_remove_generalperson_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='fullname',
        ),
        migrations.AddField(
            model_name='family',
            name='benefit',
            field=models.CharField(default=1, max_length=50, verbose_name='% Beneficio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='family',
            name='flast_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Apellido paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1, verbose_name='Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='¿Eliminado?'),
        ),
        migrations.AddField(
            model_name='family',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Job', verbose_name='Puesto de trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='life',
            field=models.BooleanField(default=True, verbose_name='¿Vive?'),
        ),
        migrations.AddField(
            model_name='family',
            name='mlast_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Apellido materno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='family',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Otra nacionaldiad'),
        ),
        migrations.AddField(
            model_name='family',
            name='place_birth',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1, verbose_name='Genero'),
            preserve_default=False,
        ),
    ]
