# Generated by Django 3.0.9 on 2020-11-18 16:43

from django.db import migrations, models
import django.db.models.deletion
import people.apps.functions


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20201118_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=20, verbose_name='Codigo del pais')),
                ('international_code', models.CharField(max_length=20, verbose_name='Codigo internacional')),
                ('national_code', models.CharField(max_length=20, verbose_name='Codigo nacional')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('phone_type', models.CharField(max_length=20, verbose_name='Tipo de telefono')),
                ('line_type', models.CharField(max_length=20, verbose_name='Tipo de linea')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
    ]
