# Generated by Django 3.0.9 on 2020-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.CharField(default=1, max_length=300, verbose_name='Ubicacion del domicilio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Avenida'), (2, 'Boulevaard'), (3, 'Calle')], null=True, verbose_name='Tipo de calle'),
        ),
        migrations.AlterField(
            model_name='address',
            name='numberOne',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero exterior'),
        ),
        migrations.AlterField(
            model_name='address',
            name='numberTwo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero interior'),
        ),
        migrations.AlterField(
            model_name='family',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='line_type',
            field=models.IntegerField(choices=[(1, 'Celular'), (2, 'Fijo')], verbose_name='Tipo de linea'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.IntegerField(choices=[(1, 'Alterno'), (2, 'Principal'), (3, 'Recados')], verbose_name='Tipo de telefono'),
        ),
    ]
