# Generated by Django 3.0.9 on 2020-12-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_treatment'),
        ('business', '0001_initial'),
        ('person', '0013_auto_20201118_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='business.Node', verbose_name='Unidad estratégica'),
        ),
        migrations.AddField(
            model_name='person',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Treatment', verbose_name='Tratamiento'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Cancelado')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Job', verbose_name='Puesto')),
                ('users_applied', models.ManyToManyField(to='person.Person', verbose_name='Usuarios que aplicaron')),
            ],
            options={
                'verbose_name': 'Vacante(Plaza)',
                'verbose_name_plural': 'Vacantes(Plazas)',
            },
        ),
    ]
