# Generated by Django 3.0.9 on 2021-01-06 23:15

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import people.apps.person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_auto_20201221_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=people.apps.person.models.Person.upload_photo, verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], default=3, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Job', verbose_name='Puesto de trabajo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='khonnect_id',
            field=models.CharField(help_text='Informacion que proviene del microservicio khonnect', max_length=40, verbose_name='Khonnect id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mlast_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.PersonType', verbose_name='Tipo de persona'),
        ),
    ]
