# Generated by Django 3.0.9 on 2021-01-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_auto_20210106_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalperson',
            name='photo',
        ),
    ]
