# Generated by Django 3.0.9 on 2021-01-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_treatment'),
        ('person', '0016_remove_generalperson_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceJob',
            new_name='JobExperience',
        ),
    ]
