# Generated by Django 3.0.9 on 2021-01-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_auto_20210106_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemergency',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona'),
        ),
    ]
