# Generated by Django 3.0.9 on 2021-01-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_person_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
