# Generated by Django 3.0.9 on 2021-01-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_person_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemergency',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Direccion'),
        ),
    ]
