# Generated by Django 3.0.9 on 2021-01-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20210119_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona'),
        ),
    ]
