# Generated by Django 3.0.9 on 2021-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_jobexperience_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='since',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='training',
            name='until',
            field=models.DateField(verbose_name='Fecha de termino'),
        ),
    ]
