# Generated by Django 3.0.9 on 2021-01-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_jobexperience_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_requested', models.IntegerField(verbose_name='Días solicitados')),
                ('departure_date', models.DateField(verbose_name='Fecha de salida')),
                ('return_date', models.DateField(verbose_name='Fecha de regreso')),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado')], default=1, verbose_name='Estatus')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='person.Person', verbose_name='Persona quien aprueba')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Vacaciones',
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
