# Generated by Django 3.0.9 on 2021-01-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_jobdepartment'),
        ('person', '0023_auto_20210120_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexperience',
            old_name='addres_company',
            new_name='address_company',
        ),
        migrations.RenameField(
            model_name='jobexperience',
            old_name='startin_salary',
            new_name='starting_salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.AddField(
            model_name='person',
            name='job_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.JobDepartment', verbose_name='Puesto de trabajo Departamento'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='since',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='until',
            field=models.DateField(verbose_name='Fecha de termino'),
        ),
    ]
