# Generated by Django 3.0.9 on 2021-01-26 17:32

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import people.apps.functions
import people.apps.person.models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20210126_1123'),
        ('business', '0003_jobdepartment'),
        ('person', '0024_auto_20210121_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unit',
            field=models.ManyToManyField(to='business.Node', verbose_name='Unidad estratégica'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=people.apps.functions.get_clean_uuid, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('document', easy_thumbnails.fields.ThumbnailerField(upload_to=people.apps.person.models.Document.upload_document, verbose_name='Documento')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.DocumentType', verbose_name='Tipo de documento')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
