# Generated by Django 3.0.9 on 2021-01-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_vacation'),
        ('person', '0024_auto_20210121_1123'),
    ]

    operations = [
    ]
