# Generated by Django 3.0.9 on 2021-01-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_auto_20210126_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia'),
        ),
    ]
