# Generated by Django 3.0.9 on 2021-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_auto_20210126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
