# Generated by Django 3.0.9 on 2021-01-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_auto_20210126_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Job', verbose_name='Puesto de trabajo'),
        ),
    ]
