# Generated by Django 3.0.9 on 2021-02-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='Reporta a'),
        ),
    ]
