# Generated by Django 3.0.9 on 2021-02-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_merge_20210125_1423'),
        ('person', '0030_person_report_to'),
    ]

    operations = [
    ]
