# Generated by Django 3.0.9 on 2021-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0032_auto_20210203_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='comment',
            field=models.TextField(blank=True, help_text='Razón por la cual se rechaza la solicitud (solo aplica para estatus rechazado)', null=True, verbose_name='Comentario'),
        ),
    ]
