# Generated by Django 3.0.9 on 2021-02-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_vacation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_by', to='person.Person', verbose_name='Persona quien rechaza'),
        ),
    ]
