# Generated by Django 3.0.9 on 2021-01-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_jobdepartment'),
        ('person', '0027_auto_20210126_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('target_gender', models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True, verbose_name='Genero')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Creado por')),
                ('target_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Node', verbose_name='Empresa')),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Job', verbose_name='Puesto')),
                ('target_person_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.PersonType', verbose_name='Tipo de persona')),
            ],
            options={
                'verbose_name': 'Notificación de usuario',
                'verbose_name_plural': 'Notificaciones de usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_read', models.BooleanField(default=False, verbose_name='¿Leído?')),
                ('date_read', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticenter.Notification', verbose_name='Notificación')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Notificación de usuario',
                'verbose_name_plural': 'Notificaciones de usuarios',
            },
        ),
    ]
