# Generated by Django 3.0.9 on 2021-01-29 17:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticenter', '0002_auto_20210127_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Mensaje'),
        ),
    ]
