# Generated by Django 3.0.9 on 2021-01-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticenter', '0003_auto_20210129_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
