# Generated by Django 3.0.9 on 2021-01-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticenter', '0003_auto_20210129_1137'),
        ('noticenter', '0005_auto_20210129_1225'),
    ]

    operations = [
    ]
