# Generated by Django 3.0.9 on 2021-01-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_auto_20210128_1235'),
        ('noticenter', '0005_auto_20210129_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='No puede ser repetido', max_length=500, verbose_name='ID del dispositivo')),
                ('mobile_os', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS')], verbose_name='Sistema operativo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
