# Generated by Django 3.0.9 on 2021-01-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticenter', '0006_merge_20210129_1232'),
        ('noticenter', '0006_userdevice'),
    ]

    operations = [
    ]
