# Generated by Django 3.0.9 on 2021-02-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_jobdepartment'),
        ('noticenter', '0007_merge_20210129_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.JobDepartment', verbose_name='Departamento'),
        ),
    ]
