# Generated by Django 3.0.9 on 2021-02-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticenter', '0008_notification_target_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noticenter.Notification', verbose_name='Notificación'),
        ),
    ]
