# Generated by Django 3.0.9 on 2021-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticenter', '0009_auto_20210203_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
    ]
