# Generated by Django 3.0.9 on 2020-12-10 19:30

from django.db import migrations, models
import django.db.models.deletion
import people.apps.business.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('person', '0010_remove_generalperson_cv'),]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=people.apps.business.models.Node.image_path)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Node')),
            ],
            options={
                'verbose_name': 'Nodo organizacional',
                'verbose_name_plural': 'Nodos organizacionales',
            },
        ),
        migrations.CreateModel(
            name='NodePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Node')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'verbose_name': 'Responsable de un nodo organizacional',
                'verbose_name_plural': 'Responsables de nodos organizacionales',
            },
        ),
    ]
