# Generated by Django 3.0.9 on 2021-01-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_auto_20210120_1431'),
        ('business', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Job')),
            ],
            options={
                'verbose_name': 'Puesto de trabajo de departamento',
                'verbose_name_plural': 'Puestos de trabajo de departamentos',
            },
        ),
    ]
