# Generated by Django 3.0.9 on 2020-10-30 19:47

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('unlimited_licenses', models.BooleanField(default=True, verbose_name='¿Licencias ilimitadas?')),
                ('num_licenses', models.IntegerField(blank=True, default=0, help_text='Aplica solo si no es ilimitado', null=True, verbose_name='Número de licencias')),
                ('available_licenses', models.IntegerField(blank=True, default=0, help_text='Numero de licencias disponibles', null=True, verbose_name='licencias disponibles')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.Client')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
